version: "3"

services:

  marketplace-public:
    image: kinecosystem/devplatform-marketplace-server:latest
    ports:
      - 80:3000
    environment:
      &app_env_vars
      APP_DEBUG: 'False'
      APP_PORT: 3000
      APP_HOST: '0.0.0.0'
      APP_NAME: 'marketplace-server'
      APP_REDIS: redis://URL:6379/0
      STATSD_HOST: http://datadog
      STATSD_PORT: 8125
      APP_PAYMENT_SERVICE: 
      APP_INTERNAL_SERVICE: http://marketplace-internal:3000
      APP_BI_SERVICE: 
      APP_DB_TYPE: postgres
      APP_DB_USERNAME: user
      APP_DB_PASSWORD: pass
      APP_DB_PORT: 5432
      APP_DB_HOST: http://URL
      APP_DB_DATABASE: ecosystem
    command: ./tests/wait-for marketplace-internal:3000 -- npm run start
    volumes:
      - .:/opt/marketplace-server


  marketplace-internal:
    image: kinecosystem/devplatform-marketplace-server:latest
    command: npm run start-internal
    ports:
      - 3000
    environment:
      <<: *app_env_vars
      APP_NAME: 'marketplace-internal'
      APP_JWT_KEYS_DIR: /opt/marketplace-server/jwt

  datadog:
    image: dd-agent
    environment:
     - API_KEY=
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/mounts:/host/proc/mounts:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
